config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    get 'top/top'
  end

  get '/end_user/mypage'=> 'end_users/end_users#show', as: 'mypage_end_user'

  namespace :admins do
    resources :genres, only:[:index, :edit, :create]
    resources :orders, only:[:index, :new]
    resources :items, only:[:index, :new, :create]
    resources :end_users, only:[:index, :show, :edit, :update]
  end

  namespace :end_users do
    
    resources :cart_items, only:[:index]
    resources :items, only:[:index, :show]
    get 'items/top'

    get 'end_users/confirm'
  end
  
  scope module: :end_users do
    resources :addresses, only:[:create, :edit, :show,:update, :destroy]
    resource :end_user, only:[:index, :edit, :update]
  end

 

  root 'end_users/items#top'
  resources :admins, only:[:show, :index, :edit]


  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }


  get '/about' => 'abouts#about', as: 'about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  acts_as_paranoid 

  enum is_deleted: {"退会済": true, "有効": false}

 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders
  has_many :order_details, through: :orders, source: :order

  validates :name, presence: true, length:{minimum: 2, maximum: 20}
  validates :kana_surname, presence: true
  validates :kana_name, presence: true
  validates :postal_code, presence: true
  validates :street_address, presence: true
  validates :phone_number, presence: true

end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
  def index
    @end_users = EndUser.with_deleted

  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    end_user = EndUser.find(params[:id])
    if end_user.update(end_user_params)
      redirect_to admins_end_users 
    else
      @end_user = end_user
      render action: :edit
    end
  end


  private
  def end_user_params
      params.require(:end_user).permit(:email, :name, :kana_surname, :kana_name,:surname, :postal_code, :street_address, :phone_number)
  end
  
end

app/controllers/end_users/addresses_controller.rb
class EndUsers::AddressesController < ApplicationController
  before_action :authenticate_end_user!
  def index
    @address = Address.new
    @addresses = Address.where(end_user_id: current_end_user.id)
  end

  def edit
    @address = Address.find(params[:id])

  end

  def update
    address = Address.find(params[:id])
    if address.update(address_params)
      redirect_to address_path(current_end_user.id)
    else
      @address = address
      render :edit
    end
  end

  def create
      address = Address.new(address_params)
      address.end_user_id = current_end_user.id
      if address.save
        redirect_to address_path(current_end_user.id)
      else
        @address = address
        @addresses = Address.all
        render :show
      end

  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to address_path(current_end_user.id)
  end

  private
    def address_params
      params.require(:address).permit(:postal_code, :street_address, :address)
    end

end

app/controllers/end_users/cart_items_controller.rb
class EndUsers::CartItemsController < ApplicationController
  before_action :authenticate_end_user!
  def index
    @total_price = 0
    current_end_user.cart_items.each do |cart_item|
      price = 0
      price = cart_item.item.price * cart_item.amount
      @total_price = @total_price + price
    end
    @total_price = @total_price * 1.10
  end

  def create
    cart_item = CartItem.new(cart_item_params)
    cart_item.end_user_id = current_end_user.id

    if current_end_user.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
     cart_item = current_end_user.cart_items.find_by(item_id: params[:cart_item][:item_id])
     cart_item.update(amount: cart_item.amount = cart_item.amount + params[:cart_item][:amount].to_i)
    else
      cart_item.save
    end
    redirect_to cart_items_path
  end


  def update
    cart_item = CartItem.find(params[:id])
    cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end
  
  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to request.referer
  end

  def destroy_all
    current_end_user.cart_items.destroy_all
    redirect_to  items_path
  end


  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/end_users_controller.rb
class EndUsers::EndUsersController < ApplicationController
  before_action :authenticate_end_user!
  def show
  end

  def edit
    
  end

  def update
    end_user = EndUser.find(current_end_user.id)
    if end_user.update(end_user_params)
      redirect_to mypage_end_user_path
    else
      render action: :edit
    end
  end

  def confirm
  end

  private
  def end_user_params
      params.require(:end_user).permit(:email, :name, :kana_surname, :kana_name,:surname, :postal_code, :street_address, :phone_number)
  end
end

app/controllers/end_users/items_controller.rb
class EndUsers::ItemsController < ApplicationController
  def index
    @genres = Genre.all
    
    if params[:genre_id].nil?
     @searches = Item.search(params[:name])
   
      @search_result = @searches.name
    else 
      @searches = Item.where(genre_id: params[:genre_id], status: 0)
      @search_result = Genre.find(params[:genre_id]).name
    end
   
    @searches = @searches.select { |data| data.genre.status_before_type_cast == 0 }

  end

  #def genres
   # @genres = Genre.all
   # @searches = Item.where(genre_id: params[:genre_id], status: 0)
   # @searches = @searches.select { |data| data.genre.status_before_type_cast == 0 }
    # render :index
  #end

  def top
  end

  def show
    @genres = Genre.all
    @item = Item.find(params[:id])
    @taxi = 1.10
    @cart_item = CartItem.new
  end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/orders_controller.rb
class EndUsers::OrdersController < ApplicationController
  before_action :authenticate_end_user!
  before_action :cart_item_check, only: [:new, :confirm, :create]
  def index
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @end_user = EndUser.find(current_end_user.id)
    @addresses = current_end_user.addresses.all
  end

  def confirm
    
    @total_price = 0
    @prices = 0
    current_end_user.cart_items.each do |cart_item|
      price = 0
      price = cart_item.item.price * cart_item.amount
      @total_price = @total_price + price
    end
    
    session[:order][:postage] = 1000

    total_prices = ((@total_price + session[:order][:postage]) * 1.10).round

    
    session[:order][:total_price] = total_prices
  end

  def create
    order = Order.new(session[:order])
    order.save
    session[:order].clear


    current_end_user.cart_items.each do |cart_item|
      order_detail = OrderDetail.new(
        item_id: cart_item.item_id,
        order_id: order.id,
        amount: cart_item.amount,
        price: cart_item.item.price
      )
      order_detail.save
    end
    #addressの追加
  
    unless session[:address].blank?
    
      Address.create(session[:address])
      session[:address].clear
    end
    
    

    current_end_user.cart_items.destroy_all
    redirect_to complete_path

  end

  def examcreate
    session[:order] = Order.new(orderexam_params)

    session[:order][:end_user_id] = current_end_user.id

    
    if params[:address_btn].to_i == 1
      session[:order][:postal_code] = current_end_user.postal_code
      session[:order][:street_address] = current_end_user.street_address
      session[:order][:address] = current_end_user.name
      redirect_to input_confirm_path

    elsif params[:address_btn].to_i == 2
      if params[:address_info][:address_info].blank?
        @order = Order.new
        @end_user = EndUser.find(current_end_user.id)
        @addresses = current_end_user.addresses.all
        render :new and return
      else
        street_address = current_end_user.addresses.find(params[:address_info][:address_info].to_i)
        session[:order][:postal_code] = street_address.postal_code
        session[:order][:address] = street_address.address
        session[:order][:street_address] = street_address.street_address
        redirect_to input_confirm_path
      end
      
    elsif params[:address_btn].to_i == 3
      if params[:order][:postal_code].blank? || params[:order][:address].blank? || params[:order][:street_address].blank?
        @order = Order.new
        @end_user = EndUser.find(current_end_user.id)
        @addresses = current_end_user.addresses.all
        render :new and return
      else    
        session[:address] = Address.new(address_params)
        session[:address][:end_user_id] = current_end_user.id
        redirect_to input_confirm_path
      end 
    else    
      redirect_to request.referer
    end

  end

  def complete
  end


  private
    def orderexam_params
      params.require(:order).permit(:payment, :street_address, :postal_code, :address)
    end
    def address_params
      params.require(:order).permit(:street_address, :postal_code, :address)
    end
    def order_params
      params.require(:order).permit(:total_price, :payment, :postal_code, :postage, :address, :street_address)
    end

    def cart_item_check
      cart_item = current_end_user.cart_items
      unless cart_item.exists?
        redirect_to items_path
      end
    end

end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/end_users/addresses_helper.rb
module EndUsers::AddressesHelper
end

app/helpers/end_users/cart_items_helper.rb
module EndUsers::CartItemsHelper
end

app/helpers/end_users/end_users_helper.rb
module EndUsers::EndUsersHelper
end

app/helpers/end_users/items_helper.rb
module EndUsers::ItemsHelper
end

app/helpers/end_users/orders_helper.rb
module EndUsers::OrdersHelper
end

app/views/end_users/addresses/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-1">
            <h2>配送先編集</h2>
            <%= form_for(@address) do |address| %>
            <table class="table">
                <tr>
                    <td>郵便番号</td>
                    <td><%= address.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "郵便番号" %></td>
                    
                </tr>
                <tr>
                    <td>住所</td>
                    <td><%= address.text_field :street_address, autofocus: true, autocomplete: "street_address", placeholder: "住所" %></td>
                </tr>
                <tr>
                    <td>宛名</td>
                    <td><%= address.text_field :address, autofocus: true, autocomplete: "address", placeholder: "宛名" %></td>
                </tr>
            </table>
            <span><%= address.submit "編集する", class: "btn btn-primary" %></span>
            <% end %>
        </div>
    </div>
    

app/views/end_users/addresses/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-1">
            <h2>配送先/登録一覧</h2>
            <%= form_for(@address) do |f| %>
            <table class="table table-hover table-inverse">
                <tbody>
                    <tr>
                         <td><%= f.label :postal_code, "郵便番号" %></td>
                          <td><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "郵便番号" %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :street_address, "住所" %></td>
                        <td><%= f.text_field :street_address, autofocus: true, autocomplete: "street_address", placeholder: "住所" %></td>
                    </tr>　
                    <tr>
                       <td><%= f.label :address, "宛名" %></td>
                        <td><%= f.text_field :address, autofocus: true, autocomplete: "address", placeholder: "宛名" %></td>
                    </tr>
                </tbody>
            </table>
            <div class="col-md-4 col-md-offset-6">
                <span><%= f.submit "登録する", class: "btn btn-primary" %></span>
            </div>
            <% end %>
        </div>
    </div>
    <br>
    <br>
    <div class="row col-md-8 col-md-offset-1">
        <table class="table">
            <thead>
                <tr>
                    <th>郵便番号</th>
                    <th>住所</th>
                    <th>宛名</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <% current_end_user.addresses.each do |address| %>
                <tr>
                    <td>〒<%= address.postal_code %></td>
                    <td><%= address.street_address %></td>
                    <td><%= address.address %></td>
                    <td><span><%= link_to "編集する", edit_address_path(address.id), class:"btn btn-primary" %></span>　<span><%= link_to "削除する", address_path(address.id), method: :delete, class: "btn btn-danger"%></span></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/end_users/addresses/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-1">
            <h2>配送先/登録一覧</h2>
            <%= form_for(@address) do |f| %>
            <table class="table table-hover table-inverse">
                <tbody>
                    <tr>
                         <td><%= f.label :postal_code, "郵便番号" %></td>
                          <td><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "郵便番号" %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :street_address, "住所" %></td>
                        <td><%= f.text_field :street_address, autofocus: true, autocomplete: "street_address", placeholder: "住所" %></td>
                    </tr>　
                    <tr>
                       <td><%= f.label :address, "宛名" %></td>
                        <td><%= f.text_field :address, autofocus: true, autocomplete: "address", placeholder: "宛名" %></td>
                    </tr>
                </tbody>
            </table>
            <div class="col-md-4 col-md-offset-6">
                <span><%= f.submit "登録する", class: "btn btn-primary" %></span>
            </div>
            <% end %>
        </div>
    </div>
    <br>
    <br>
    <div class="row col-md-8 col-md-offset-1">
        <table class="table">
            <thead>
                <tr>
                    <th>郵便番号</th>
                    <th>住所</th>
                    <th>宛名</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <% @addresses.each do |address| %>
                <tr>
                    <td>〒<%= address.postal_code %></td>
                    <td><%= address.street_address %></td>
                    <td><%= address.address %></td>
                    <td><span><%= link_to "編集する", edit_address_path(address.id), class:"btn btn-primary" %></span>　<span><%= link_to "削除する", address_path(address.id), method: :delete, class: "btn btn-danger"%></span></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>